### ISSUE TITLE
make  error during server build

### ISSUE THREAD

**Issue by Robinatp** [mobvoi/wenet#160]
cmake version 3.19.4

gcc version 9.3.0 (GCC)

cmake successfully,but make  error when runtime server building

wenet-main/runtime/server/x86/fc_base/libtorch-src/lib/libtorch_cpu.so: undefined reference to `lgammaf@GLIBC_2.23'
wenet-main/runtime/server/x86/fc_base/libtorch-src/lib/libtorch_cpu.so: undefined reference to `lgamma@GLIBC_2.23'

please look at it, thanks!

**Comment by placebokkk** [comment]
make sure you have followed the readme to setup env. 

install miniconda

```
conda create -n wenet python=3.8
conda activate wenet
pip install -r requirements.txt
conda install pytorch==1.6.0 cudatoolkit=10.1 torchaudio -c pytorch
```

This discuss may help if you are using nightly version pytorch:
https://discuss.pytorch.org/t/glibc-linker-errors-with-libtorch-nightly-build/66030

**Comment by paklau99988** [comment]
Not work with cuda 10.2?

**Comment by pengzhendong** [comment]
@Robinatp Could you try a different compiler? This [error](https://github.com/pytorch/pytorch/issues/27834) may be caused by the compiler.
@paklau99988 The runtime only uses the cpu for inference.

**Comment by robin1001** [comment]
Maybe your problem is about C++ ABI.

Please try the Pre-cxx11 ABI LibTorch:https://download.pytorch.org/libtorch/cpu/libtorch-shared-with-deps-1.6.0%2Bcpu.zip,
replace libtorch URL with this link and add "-D_GLIBCXX_USE_CXX11_ABI=0" in your build flags.

**Comment by guodongma-asr** [comment]
Hi all, Has the problem been solved? I ran into it, too.

**Comment by guodongma-asr** [comment]
> Maybe your problem is about C++ ABI.
> 
> Please try the Pre-cxx11 ABI LibTorch:https://download.pytorch.org/libtorch/cpu/libtorch-shared-with-deps-1.6.0%2Bcpu.zip,
> replace libtorch URL with this link and add "-D_GLIBCXX_USE_CXX11_ABI=0" in your build flags.

Hi, I miss the same issue, so I do this modification. But I get a new errer:

**Comment by guodongma-asr** [comment]
> Maybe your problem is about C++ ABI.
> 
> Please try the Pre-cxx11 ABI LibTorch:https://download.pytorch.org/libtorch/cpu/libtorch-shared-with-deps-1.6.0%2Bcpu.zip,
> replace libtorch URL with this link and add "-D_GLIBCXX_USE_CXX11_ABI=0" in your build flags.

Hi, I miss the same issue, so I do this modification as you said above. But I get new error:  websocket_client_main.cc:(.text._ZN6google17MakeCheckOpStringIiiEEPSsRKT_RKT0_PKc[_ZN6google17MakeCheckOpStringIiiEEPSsRKT_RKT0_PKc]+0x6c): undefined reference to `google::base::CheckOpMessageBuilder::NewString()'
   collect2: error: ld returned 1 exit status (centos 7.5  gcc7.1,0  cmake 3.17.0) .  Thank you in advance.

**Comment by MaGuodong0712** [comment]
Hi, I get the same issue, so I do this modification as you said above. But new error happened: 
```
websocket_client_main.cc:(.text._ZN6google17MakeCheckOpStringIiiEEPSsRKT_RKT0_PKc[_ZN6google17MakeCheckOpStringIiiEEPSsRKT_RKT0_PKc]+0x6c): undefined reference to `google::base::CheckOpMessageBuilder::NewString()'
collect2: error: ld returned 1 exit status 
```

mechine: centos 7.5 gcc7.1,0 cmake 3.17.0 . 
Thank you in advance.

**Comment by jetou** [comment]
> 
thank you your answer solves my problem.
